       typedef unsigned z ;typedef                                                  unsigned char  y;                                                           typedef struct{                                     z a,b,c,d;y e,f[32];z g,h             
       ;}x;typedef  char A;typedef                                                  void* B; typedef                                                            struct{A a[216];}                                   C;C* fopen(A*,A*);typedef             
(*D)() ;volatile a[5] [4]={{ },{},{ },{},{                                   4022250974u}},b[4]={0,0,4022250973u                                             ,1},c,d,e[16],f,g                                   ,h;x i,j ;D k[4] ;B l;C* m;n(){          
return d<4;}o(){return d>=0;}p(){return c<                                   4;} q( ){ return c >=0 ;} A* r=                                                 "\xe2\x96\x88\0 \x80\x84"                           ;A s[18][ 20]={"","\x1b[38;2;2"          
"39;227;222m","\x1b[38;2;224;197;152m","\x1b"                            "[38;2;239;178;123m","\x1b[38;2;247;1"                                             "50;99m","\x1b[3"                               "8;2;247;125;99m","\x1b[38;2;247;93;58m"     
,"\x1b[38;2;239;206;115m","\x1b[38;2;239;202"                            ";99m","\x1b[38;2;239;198;82m","\x1b["                                             "38;2;239;198;66m"                              ,"\x1b[38;2;239;194;49m" ,"\x1b[38;2;"       
"107;2"                        "02;16m","\x1b"                       "[38;2;99;190;8m"          , "\x1b[38;2;"                                          "90;18"   "6;0m"  ,                             "\x1b[38;2;82;17"              "0;0m","\x1b["   
                                   "38;2;74;138;"                     "16m","\x1b"                       "[38;2;"                                    "90;138;2"   "47m"},t[2                            ][3][31],u                        [18][15]={   
                                   "      ","   "                     "2  ","  "                        " 4  "," "                                   "  8  "," "  " 16  "," "                           " 32  " ,                         "  64  "," " 
                                      " 128 "," "                    " 256 "," "                       " 512 " ,                                    " 1024 "      , " 2048 "                            ," 4096 ",                        " 8192 "," " 
                                      "16384"," "                    "32768"," "                       "65536" ,                                    "131072"      };void  E(                            ){m=fopen(                        r,"rb");if   
                                      (!m)return                 ;fseek(m,0,2);                        c=ftell(m )/4;                            fseek(m,0,0      );z _ [c];                            fread(_,4,c                       ,m);fclose   
                                      (m);for(d=                 0;d<c;++d){if(                        _[d]==a[4][0])                            for(f=0;f<       4;++f)for(                            g=0;g<4;++                        g){_[d-16+   
                                      g+f*4]=a[f                 ][g];}if(_                               [d]==b[2])                        {_[d-2]=*b          ;_[d-1]=b[                            1];}}m=fopen                      ( "data."    
                                   "bin","wb");if                 (!m)return                               ;fwrite(_,                        4,c,m);              fclose(m);                               if(rename(                 "data.bin"       
                                   ,r)==0){A*E[]=                 {"chmod","+"                             "x", r, 0}                        ;execvp              ("chmod",E                               );}}void w                 (){tcsetattr     
                                   (0,2, &i);                     printf("\x1b"                             "[J\x1b"                      "[H\x1b[m"              );}main(z                                    H,A**G){O:for(c=0;c<4;++c)for(d          
                                   =0;d<4;++d                     )if(a[c][d                               ])b[3]=0;k                     [0]=n;k[1]              =o;k[2]=p;                                   k[3]=q;for(c=0;c<30;++c){t[0][0          
                               ][c]=r[4];                        t[0][1][c]                               =r[4];t[0]                 [2][c]=r[4                 ];t[1][0][                                      c]=r[(c%3==0)?0:(c%3==1)              
                               ?1:2];t[1]                        [1][c]=r[(                               c%3==0)?0:                 (c%3==1)?1                 :5];t[1][2                                      ][c]=r[(c%3==0)?0:(c%3==              
                            1)?1:6];}t[1][                        1][2]=r[2]                               ;t[1] [1][                 29]=r[2]                    ;t[1][2][2                               ]=r[2];t[1][2][29]=r[2];for(c=0;c<3;++       
                            c){t[0][c][10]                        =r[3];t[1]                               [c][30]=r[                 3];}srand                   (time (0 )                               );tcgetattr(0,&i);atexit(w);j=i;j.a&=~       
                        2046;j.f[5]=0;                            j.b&=~++j.                               f[5];j.c|=              60;j. d&=~                     100011;j.f[                           6]=0;tcsetattr                 (0,2,&j);for(;   
                     ;){f=0;for(c=0                               ;c<4; ++c)                               for(d=0;d<4         ;++d)if(!a                        [c][d])e[f                        ++]=c+4*d;if(!                        f)goto v;g=rand
                     ()%f;c=e[g]%4;                               d=e[g ]/4;                               if(b[3])a[c         ][d]=(rand                        ()%10==0)?                        4:2;v:if(*b>b[                        1]) b[1 ]=* b; 
                 printf("\x1b["                                    "H\x1b["                                "K\x1b[mSco"     "re: %d\tHigh score: %d\r\n",*b,b[1]);for(c=0;c<4;++c)for(d              =0;d<5;++d                               ){for(f=0; 
                 f<4;++f ){g=0;                                   if(a[f][c]>                              0) g =31 -       __builtin_clz(a[f][c]);printf("%s",s[g]);if(d==0||d==4)printf(           "%s",t[g!=                               0][0]);if( 
              d== 1) printf(                                      "%s",t[g!=0][1])                      ;if(d==2)if(g)       printf("%s %s %s",r,u[g],r);else printf("  %s  ",u[g]);if(d              ==3)printf                               ("%s", t[g 
              !=0][2]);}printf                                    ("\r\n") ;}for                        (;;){c= 0;d=0;       while((d=read(0,&c,1))<0);h=(d==0)?'\0':c;b[3]=0;switch(h){              case'r':for                              (c=0; c<4; 
          ++c)for(d=0;d<                                             4;++d)a[c]                        [d]=0;*b=0          ;b[3]=1;goto O; case'q':r=*G;E() ;return 0;case'w':case'a':              case's':case                             'd':l=&&E; 
       C:switch (h ){                                                 case'w':case                      's':for(c=                                                 0;c<4;++c)                        for(d=(h=='w')                        ?0:3;k[h=='s'] 
       ();d+=h=='w'?1                                                 :-1)if(a[c                        ][d]){f=d;                                                 if(h=='w')                        for(g=d-1;g>=0                        ;--g){if(!a[c] 
   [g])f=g;}else                                                     for(g=d+1;g<4;++g          ){if(!a[c][g])f=g                                                 ;}if(f!=d)                            {a[c][f]=a[c][                 d];a[c][d]=0;b   
   [3]=1;}}break;                                                    case'a': case'd':          for(d=0;d<4;++d)for                                               (c=(h=='a'                            )?0: 3;k[ 2+(h                 =='d')]();c+=h   
=='a'?1:-1)if(a[c][d]){f =c;if(h=='a')for(g=c-1;g                        >=0;--g){if(!a[g][d])f=g;}else for(g=c+                                                   1;g<4;++g)                            {if(!a[g][d])f=g;}if(f!=c){a[f][d]=a[c][d];a[   
c][d]=0;b[3]=1;}}break;}goto*l;E:switch(h){case'w'                       :case's':f=h=='w'?1:-1 ;for(c=0;c<4;++                                                    c)for( d=h                            =='w'?1:2; k[h=='s']();d+=f)if(a[c][d])if(a[c]  
[d-f]==a[c][d]){a[c][d-f]*=2;*b+=a[c][d-f];a[c][d                            ]=0;b[3]= 1;}break;case'a':case                                                        'd':f=h=='a'                             ?1:-1;for(d=0;d<4 ;++d)for(c=h=='a'?1:       
2;k[2+(h=='d')]();c+=f)if(a[c][d])if(a[c-f][d]==a                                   [c][d]){a[c-f][d]                                                               *=2;*b+=a[                                      c-f][d];a[c][d]=0;b[3]=1              
;} break; }l =&& _; goto C ;default :; }} _: ;} }                                   /* ChaosPotato42 */                                                                                                                                                   
