       typedef unsigned z;typedef                                                          unsigned char y;                                                                     typedef struct{                                           z a,b,c,d;y e,f[32];z g,h;                 
       }x;a[4][4],b=0,c,d,e[16],f,g,h                                                      ,i,j,k,l,m,n,o,p;x                                                                  q,r;char*s[]={                                           "m",";239;227;222m",                       
";224;197;152m",";239;178;123m",";247;150;99m"                                       ,";247;125;99m",";247;93;58m",                                                          ";239;206;115m",                                          ";239;202;99m",";239;198;82m",                
";239;198;66m",";239;194;49m",";107;202;16m",                                        ";99;190;8m",";90;186;0m",";82;170;0m"                                                   ,";74;138;16m",                                          ";90;138;247m"};char*t[][3]={{                
"          ","          ","          "},{"\xe2"                                 "\x96""\x88""\xe2""\x96""\x88""\xe2""\x96"                                                  "\x88""\xe2""\x96"                                   "\x88""\xe2""\x96""\x88""\xe2""\x96""\x88"        
"\xe2""\x96""\x88""\xe2""\x96""\x88""\xe2""\x96"                                "\x88""\xe2""\x96""\x88","\xe2""\x96""\x88"                                                 "\xe2""\x96""\x80"                                   "\xe2""\x96""\x80""\xe2""\x96""\x80""\xe2"        
"\x96"                            "\x80""\xe2""\x96"                         "\x80""\xe2""\x96"            "\x80""\xe2""\x96"                                            "\x80"    "\xe2""\x96"                              "\x80""\xe2""\x96"                 "\x88","\xe2"     
"\x96"                            "\x88""\xe2""\x96"                         "\x84""\xe2""\x96"            "\x84""\xe2""\x96"                                            "\x84"    "\xe2""\x96"                              "\x84""\xe2""\x96"                 "\x84""\xe2""\x96"
                                      "\x84""\xe2""\x96"                    "\x84""\xe2"                          "\x96""\x84"                                      "\xe2""\x96"   "\x88"}};char                            *u[]={                               "          "    
                                      ,"\xe2""\x96"                         "\x88""    2   "                       "\xe2""\x96"                                      "\x88","\xe2"  "\x96""\x88"                             "    4   "                           "\xe2""\x96"   
                                          "\x88","\xe2"                      "\x96""\x88"                         "    8   "                                        "\xe2"         "\x96""\x88"                              ,"\xe2""\x96"                         "\x88""   16   "
                                          "\xe2""\x96"                       "\x88","\xe2"                        "\x96""\x88"                                      "   32   "    "\xe2""\x96"                             "\x88","\xe2"                         "\x96""\x88"   
                                          "   64   "                     "\xe2""\x96""\x88"                        ,"\xe2""\x96"                                "\x88""   128  "   "\xe2""\x96"                             "\x88","\xe2"                         "\x96""\x88"   
                                          "   256  "                     "\xe2""\x96""\x88"                        ,"\xe2""\x96"                                "\x88""   512  "   "\xe2""\x96"                             "\x88","\xe2"                         "\x96""\x88"   
                                          "  1024  "                     "\xe2""\x96"                                  "\x88","\xe2"                        "\x96""\x88"           "  2048  "                                "\xe2""\x96"                           "\x88","\xe2" 
                                          "\x96""\x88"                   "  4096  "                                   "\xe2""\x96"                          "\x88","\xe2"          "\x96""\x88"                              "  8192  "                            "\xe2""\x96"   
                                      "\x88","\xe2"                     "\x96""\x88"                                   "  16384 "                            "\xe2"                  "\x96""\x88"                                   ,"\xe2""\x96"                  "\x88""  32768 "  
                                      "\xe2""\x96""\x88"                ,"\xe2""\x96"                                 "\x88""  65536 "                      "\xe2"                 "\x96""\x88"                                   ,"\xe2""\x96"                  "\x88"" 131072 "  
                                      "\xe2""\x96"                       "\x88"};void                                 w(){tcsetattr                     (0,2,&q);                  printf("\x1b"                                      "[J""\x1b""[H""\x1b""[m");}main(){            
                                      srand(time(                        0));tcgetattr                                 (0,&q);atexit                     (w);r=q;r.a                &=~2046;r.b                                       &=~1;r.c|=60;r.d&=~100011;r.f[6]=0            
                                  ;r.f[5]=1;                           tcsetattr(0                                   ,2,&r);for(                    ;;){f=0;for                    (h=0;h<4;++                                            h){for(g=0;g<4;++g){if(!a[                
                                  g][h]){e[f                           ++]=g+4*h;}                                   }}if(!f)goto                   v;i=rand()                    %f;g=e[i]%4                                            ;h=e[i]/4;a[g][h]=(rand()%                
                              10==0)?4:2;v:                            printf("\x1b"                                  "[H""\x1b"                     "[K""\x1b"                     "[mScore: %d"                                 "\r\n",b);for(h=0;h<4;++h){for(j=0;j<5;++        
                              j){for(g=0;g<4                           ;++g){k=0;if                                  (a[g][h]>0)                    {k=31-                         __builtin_clz                                  (a[g][h]);}printf("\x1b""[38;2%s",s[k]);if       
                          (j==0||j==4)printf                           ("%s",t[k!=                                   0][0]);if(j                ==1)printf(                        "%s",t[k!=0                               ][1]);if(j==2)                     printf("%s",u[k    
                       ]);if(j==3)printf                                 ("%s",t[k!=                                   0][2]);}printf         ("\r\n");}}                           for(;;){c=                           0;d=0;while((d=                           read(0,&c,1))<
                       0);p=(d==0)?'\0'                                  :c;switch(p                                   ){case'q':             return 0;case                          'w':case'a'                          :case's':case'd'                         :switch(p){case
                   'w':{for(g=0;g<                                       4;++g){for(                                   h=0;h<4;++h        ){if(a[g][h]){l=h;for(m=h-1;m>=0;--m){if(!a[g][m])l=m;}if(l!=h){                a[g][l]=a[g                                   ][h];a[g][h
                   ]=0;}}}}}break;                                       case'a':{for                                  (h=0;h<4;++        h){for(g=0;g<4;++g){if(a[g][h]){n=g;for(o=g-1;o>=0;--o){if(!a[o]                [h])n=o;}if                                   (n!=g){a[n]
               [h]=a[g][h];a[g                                          ][h]=0;}}}}}break                         ;case's':{for(        g=0;g<4;++g){for(h=3;h>=0;--h){if(a[g][h]){l=h;for(m=h+1;m<4;++m)                {if(!a[g][m                                   ])l=m;}if(l
               !=h){a[g][l]=a[                                          g][h];a[g][h]=0                           ;}}}}}break;case      'd':{for(h=0;h<4;++h){for(g=3;g>=0;--g){if(a[g][h]){n=g;for(o=g+1                ;o<4;++o){if                                  (!a[o][h])n
           =o;}if(n!=g){a                                                  [n][h]=a[g]                           [h];a[g][h]            =0;}}}}}break;}switch(p){case'w':{for(g=0;g<4;++g){for(h=1;h<4;++               h){if(a[g][                                   h]){if(a[g
           ][h-1]==a[g][h                                                  ]){a[g][h-1                           ]*=2;b+=a[g            ][h-1];a[g][h]=0;}}}}}break;case'a':{for(h=0;h<4;++h){for(g=1;g<                4;++g){if(a                                    [g][h]){if(
       a[g-1][h]==a[g                                                      ][h]){a[g-1                           ][h]*=2;b+=                                                      a[g-1][h];                           a[g][h]=0;}}}}}                           break;case's':
       {for(g=0;g<4;++                                                     g){for(h=2;                           h>=0;--h){if                                                     (a[g][h]){                           if(a[g][h+1]==a                           [g][h]){a[g][h
   +1]*=2;b+=a[g]                                                          [h+1];a[g][h]=0;}}}            }}break;case'd':{for                                                    (h=0;h<4;++                              h){for(g=2;g>=0                    ;--g){if(a[g][h    
   ]){if(a[g+1][h                                                          ]==a[g][h]){a[g+1][            h]*=2;b+=a[g+1][h]                                                      ;a[g][h]=0;                               }}}}}break;}switch                 (p){case'w':{for  
(g=0;g<4;++g){for(h=0;h<4;++h){if(a[g][h]){l=h;for(m=                           h-1;m>=0;--m){if(!a[g][m])l=m;}if(l!=h){a[                                                          g][l]=a[g][                               h];a[g][h]=0;}}}}}break;case'a':{for(h=0;h<4;++h)    
{for(g=0;g<4;++g){if(a[g][h]){n=g;for(o=g-1;o>=0;--o)                           {if(!a[o][h])n=o;}if(n!=g){a[n][h]=a[g][h]                                                          ;a[g][h]=0;                               }}}}}break;case's':{for(g=0;g<4;++g){for(h=3;h>=0    
;--h){if(a[g][h]){l=h;for(m=h+1;m<4;++m){if(!a[g][m])                               l=m;}if(l!=h){a[g][l]=a[g][h];a[g]                                                              [h]=0;}}}}}                                   break;case'd':{for(h=0;h<4;++h){for(g=3;g>=       
0;--g){if(a[g][h]){n=g;for(o=g+1;o<4;++o){if(!a[o][h]                               )n=o;}if(n!=g){a[n][h]=a[g][h];a[g                                                              ][h]=0;}}}}                                   }break;}goto _;default:}}_:}}